### ISSUE TITLE
Redshift: `attribution_overview` can't identify type for `spend`

### ISSUE THREAD

**Issue by jethron** [snowplow/dbt-snowplow-attribution#9]
## Describe the bug
When building `attribution_overview` with no `snowplow__spend_source` defined, the `spend` column in the CTEs is always the `null` value; when this model tries to aggregate the values via `min(spend)`, it is unable to find an appropriate type and produces a `ERROR: failed to find conversion function from "unknown" to text` error.

## Steps to reproduce
Run the attribution models on Redshift without specifying a `snowplow__spend_source` configuration.

## Expected results
The model should run successfully, producing 0/null for `spend`.

## Actual results
The model fails to build, producing an error.

## Screenshots and log output
![image](https://github.com/snowplow/dbt-snowplow-attribution/assets/1646397/43cc013a-e49e-4db0-ae68-b57dacd62573)

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

## Additional context
Casting the null to something more specific in the CTEs seems to resolve the issue:
`cast(null as double precision) as spend`

## Are you interested in contributing the fix?
If you like.

**Comment by agnessnowplow** [comment]
Thank you for raising this issue and apologies for not getting back to you earlier on this. The day this was raised we released [v0.2.0](https://github.com/snowplow/dbt-snowplow-attribution/releases/tag/0.2.0) which I just checked should already fix this issue. An upgrade should solve this therefore I'm closing this for now.
